import {
  decorateBlock,
  decorateBlocks,
  decorateButtons,
  decorateIcons,
  decorateSections,
  loadBlock,
  loadSections,
} from './aem.js';
import { decorateRichtext } from './editor-support-rte.js';
import { decorateMain } from './scripts.js';



// Code Generated by Sidekick is for learning and experimentation purposes only.

// Code Generated by Sidekick is for learning and experimentation purposes only.

(function() {

  var currentUserEndpoint = "/libs/cq/security/userinfo.json";

  fetch(currentUserEndpoint)
      .then(response => response.json())
      .then(data => {
          var userName = data.userName;
          console.log(`Username123: ${userName}`);
          
          // Construct the new API endpoint with the userName as a query parameter
          var authorizablesEndpoint = `/bin/security/authorizables.json?filter=${encodeURIComponent(userName)}&_charset_=utf-8`;

          // Call the new API endpoint
          return fetch(authorizablesEndpoint);
      })
      .then(response => response.json())
      .then(authorizablesData => {
          console.log('Authorizables Data:', authorizablesData);

          // Check if the user is a member of "Prudential Super Authors"
          var isMember = authorizablesData.authorizables.some(authorizable => 
              authorizable.memberOf.some(group => group.id === "Prudential Super Authors")
          );

          if (isMember) {
              alert('Yes');
          }
      })
      .catch(error => console.error('Error fetching user information or authorizables data:', error));

})();



function addMetaTag() {
  const meta = document.createElement('meta');
  meta.name = "urn:adobe:aue:config:disable";
  meta.content = "publish";
  document.head.appendChild(meta);
  console.log('Meta tag added:', meta);
}

addMetaTag();


async function applyChanges(event) {
  // redecorate default content and blocks on patches (in the properties rail)
  const { detail } = event;

  const resource = detail?.request?.target?.resource // update, patch components
    || detail?.request?.target?.container?.resource // update, patch, add to sections
    || detail?.request?.to?.container?.resource; // move in sections
  if (!resource) return false;
  const updates = detail?.response?.updates;
  if (!updates.length) return false;
  const { content } = updates[0];
  if (!content) return false;

  const parsedUpdate = new DOMParser().parseFromString(content, 'text/html');
  const element = document.querySelector(`[data-aue-resource="${resource}"]`);

  

  if (element) {
    if (element.matches('main')) {
      const newMain = parsedUpdate.querySelector(`[data-aue-resource="${resource}"]`);
      newMain.style.display = 'none';
      element.insertAdjacentElement('afterend', newMain);
      decorateMain(newMain);
      decorateRichtext(newMain);
      await loadSections(newMain);
      element.remove();
      newMain.style.display = null;
      // eslint-disable-next-line no-use-before-define
      attachEventListners(newMain);
      return true;
    }

    const block = element.parentElement?.closest('.block[data-aue-resource]') || element?.closest('.block[data-aue-resource]');
    if (block) {
      const blockResource = block.getAttribute('data-aue-resource');
      const newBlock = parsedUpdate.querySelector(`[data-aue-resource="${blockResource}"]`);
      if (newBlock) {
        newBlock.style.display = 'none';
        block.insertAdjacentElement('afterend', newBlock);
        decorateButtons(newBlock);
        decorateIcons(newBlock);
        decorateBlock(newBlock);
        decorateRichtext(newBlock);
        await loadBlock(newBlock);
        block.remove();
        newBlock.style.display = null;
        return true;
      }
    } else {
      // sections and default content, may be multiple in the case of richtext
      const newElements = parsedUpdate.querySelectorAll(`[data-aue-resource="${resource}"],[data-richtext-resource="${resource}"]`);
      if (newElements.length) {
        const { parentElement } = element;
        if (element.matches('.section')) {
          const [newSection] = newElements;
          newSection.style.display = 'none';
          element.insertAdjacentElement('afterend', newSection);
          decorateButtons(newSection);
          decorateIcons(newSection);
          decorateRichtext(newSection);
          decorateSections(parentElement);
          decorateBlocks(parentElement);
          await loadSections(parentElement);
          element.remove();
          newSection.style.display = null;
        } else {
          element.replaceWith(...newElements);
          decorateButtons(parentElement);
          decorateIcons(parentElement);
          decorateRichtext(parentElement);
        }
        return true;
      }
    }
  }

  return false;
}

// Code Generated by Sidekick is for learning and experimentation purposes only.

function attachEventListners(main) {
  [
    'aue:content-patch',
    'aue:content-update',
    'aue:content-add',
    'aue:content-move',
    'aue:content-remove',
    'aue:content-copy',
  ].forEach((eventType) => main?.addEventListener(eventType, async (event) => {
    if (eventType === 'aue:content-add')  {
     
      return;
    }

    event.stopPropagation();
    const applied = await applyChanges(event);
    if (!applied) window.location.reload();
  }));
}



attachEventListners(document.querySelector('main'));
